# Generated by Django 5.1.2 on 2024-10-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0003_alter_customuser_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.CharField(blank=True, choices=[('CSE', 'B.Tech(Computer Science Engineering) '), ('EC', 'B.Tech(Electronics & Communication Engineering)'), ('EEE', 'B.Tech(Electrical & Electronics Engineering)'), ('CHE', 'Diploma in Computer Hardware Engineering'), ('EL', 'Diploma in Electronics Engineering'), ('DEEE', 'Diploma in Electrical & Electronics Engineering'), ('MCA', 'MCA')], max_length=4, null=True),
        ),
    ]
