# Generated by Django 5.1.2 on 2024-10-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0004_alter_customuser_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.CharField(choices=[('CSE', 'B.Tech(Computer Science Engineering) '), ('EC', 'B.Tech(Electronics & Communication Engineering)'), ('EEE', 'B.Tech(Electrical & Electronics Engineering)'), ('CHE', 'Diploma in Computer Hardware Engineering'), ('EL', 'Diploma in Electronics Engineering'), ('DEEE', 'Diploma in Electrical & Electronics Engineering'), ('MCA', 'MCA')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='guard_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ph_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reg_no',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sem',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
    ]
