# Generated by Django 5.1.2 on 2024-10-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='past_stud',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
