# Generated by Django 5.1.2 on 2024-10-20 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0011_rename_leave_employeeleave_employee_ph_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
