# Generated by Django 5.1.2 on 2024-10-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0013_employeeleave_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelBillSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perDay_fixedCharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('broadband', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Hostel Bill Settings',
                'verbose_name_plural': 'Hostel Bill Settings',
            },
        ),
    ]
