# Generated by Django 5.1.2 on 2024-10-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0016_alter_expenditure_expenditure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelbillsettings',
            name='emp_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
