# Generated by Django 5.1.2 on 2024-10-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0017_hostelbillsettings_emp_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
