# Generated by Django 5.1.2 on 2024-10-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelbilldetail',
            name='broadband',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelbilldetail',
            name='electricity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelbilldetail',
            name='maintenence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
