# Generated by Django 5.1.2 on 2024-10-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_hostelbilldetail_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelbilldetail',
            name='due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostelbilldetail',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('mark_as_paid', 'mark_as_paid'), ('partially_paid', 'partially_paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=20),
        ),
    ]
