# Generated by Django 5.1.2 on 2024-10-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_hostelbilldetail_due_hostelbilldetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelbilldetail',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostelbilldetail',
            name='transactionID',
            field=models.TextField(blank=True, default=''),
        ),
    ]
